# fly.toml app configuration file generated for nexora-learning-logs55 on 2025-09-04T05:28:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'websynthapi'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
